# Generated by Django 6.0.4 on 2026-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_doctorprofile_specialization'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleexception',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='weeklyschedule',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='scheduleexception',
            unique_together={('doctor', 'exception_date')},
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'start_datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
