# Generated by Django 6.0.4 on 2026-04-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='consultation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='emr.consultationrecord'),
        ),
        migrations.AlterField(
            model_name='requestedtest',
            name='consultation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tests', to='emr.consultationrecord'),
        ),
    ]
